name: sandbox
description: sandbox
inputs:
  IS_LATEST:
    description: 'Indicate whether the images is latest'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Test IS_LATEST flag
      shell: bash
      run: if [ "${{ inputs.IS_LATEST }}" == "true" ]; then echo "TRUE"; else echo "FALSE"; fi
