name: build-feature
on:
  push:
    branches:
      - 'feature/ci-enhancement'
jobs:
  spark-images:
    name: Sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: IS_LATEST is TRUE
        uses: ./.github/actions/sandbox
        with:
          IS_LATEST: "true"
      - name: IS_LATEST is FALSE
        uses: ./.github/actions/sandbox
        with:
          IS_LATEST: "false"
